name: "CI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [ "published" ]

defaults:
  run:
    shell: "bash"

env:
  CI_PRERELEASE: "${{ github.event_name == 'push' }}"
  CI_RELEASE: "${{ github.event_name == 'release' }}"
  STACK_VERSION: "2.7.3"

jobs:
  build:
    strategy:
      fail-fast: false # do not cancel builds for other OSes if one fails
      matrix:
        include:
          - # If upgrading the Haskell image, also upgrade it in the lint job below
            os: "ubuntu-latest"
            image: "haskell:8.10.7-stretch@sha256:100f8fb7d7d8d64adb5e106fe8136b8d4cbdc03aeb2cbd145a7597d74b69bafb"
          - os: "macOS-10.15"
          - os: "windows-2019"

    runs-on: "${{ matrix.os }}"
    container: "${{ matrix.image }}"

    outputs:
      do-not-prerelease: "${{ steps.build.outputs.do-not-prerelease }}"
      version: "${{ steps.build.outputs.version }}"

    steps:
      - # We need a proper Git repository, but the checkout step will unpack a tarball instead of doing a clone
        # if the Git version is less than 2.18.
        name: "(Linux only) Install a newer version of Git"
        if: "${{ runner.os == 'Linux' }}"
        run: |
          . /etc/os-release
          echo deb http://deb.debian.org/debian "$VERSION_CODENAME"-backports main >> /etc/apt/sources.list
          apt-get update && apt-get install -y git/"$VERSION_CODENAME"-backports
      - uses: "actions/checkout@v2"

      - uses: "actions/setup-node@v1"
        with:
          node-version: "12"

      - id: "haskell"
        name: "(Non-Linux only) Install Haskell"
        if: "${{ runner.os != 'Linux' }}"
        uses: "haskell/actions/setup@v1"
        with:
          enable-stack: true
          stack-version: "${{ env.STACK_VERSION }}"
          stack-no-global: true

      - name: "(Linux only) Check Stack version and fix working directory ownership"
        if: "${{ runner.os == 'Linux' }}"
        run: |
          [ "$(stack --numeric-version)" = "$STACK_VERSION" ]
          chown root:root .

      - uses: "actions/cache@v2"
        with:
          path: |
            /root/.stack
            ${{ steps.haskell.outputs.stack-root }}
          key: "${{ runner.os }}-ubiqcous-${{ hashFiles('stack.yaml') }}"

      - name: "(Windows only) Configure Stack to store its programs in STACK_ROOT"
        # This ensures that the local GHC and MSYS binaries that Stack installs
        # are included in the cache. (This behavior is the default on
        # non-Windows OSes.)
        if: "${{ runner.os == 'Windows' }}"
        run: |
          mkdir -p "$STACK_ROOT"
          echo "local-programs-path: $STACK_ROOT/programs" > $STACK_ROOT/config.yaml

      - id: "build"
        run: "ci/fix-home ci/build.sh"

      - name: "(Linux only) Build the entire package set"
        if: "${{ runner.os == 'Linux' }}"
        # We build in this directory in build.sh, so this is where we need to
        # launch `stack exec`. The actual package-set building happens in a
        # temporary directory.
        working-directory: "sdist-test"
        # The presence or absence of the --haddock flag changes the location
        # into which stack places all build artifacts. Since we use --haddock
        # in our CI builds, in order to actually get stack to find the purs
        # binary it created, we need to use the flag here as well.
        run: "../ci/fix-home stack --haddock exec ../ci/build-package-set.sh"

      - name: Verify that 'libtinfo' isn't in binary
        if: runner.os == 'Linux'
        working-directory: "sdist-test"
        run: |
          if [ $(ldd $(stack path --local-doc-root)/../bin/purs | grep 'libtinfo' | wc -l) -ge 1 ]; then
            echo "libtinfo detected"
            ldd $(stack path --local-doc-root)/../bin/purs | grep 'libtinfo'
            exit 1
          fi

      - name: "(Release/prerelease only) Create bundle"
        if: "${{ env.CI_RELEASE == 'true' || (env.CI_PRERELEASE == 'true' && steps.build.outputs.do-not-prerelease != 'true') }}"
        run: |
          os_name="${{ runner.os }}"
          case "$os_name" in
            Linux)
              bundle_os=linux64;;
            macOS)
              bundle_os=macos;;
            Windows)
              bundle_os=win64;;
            *)
              echo "Unknown OS name: $os_name"
              exit 1;;
          esac
          cd sdist-test
          ../ci/fix-home bundle/build.sh "$bundle_os"

      - name: "(Prerelease only) Upload bundle"
        if: "${{ env.CI_PRERELEASE == 'true' && steps.build.outputs.do-not-prerelease != 'true' }}"
        uses: "actions/upload-artifact@v3"
        with:
          name: "${{ runner.os }}-bundle"
          path: |
            sdist-test/bundle/*.sha
            sdist-test/bundle/*.tar.gz

      - name: "(Release only) Publish bundle"
        if: "${{ env.CI_RELEASE == 'true' }}"
        # Astonishingly, GitHub doesn't currently maintain a first-party action
        # for uploading assets to GitHub releases! This is the best third-party
        # one I could find, but as this step handles a token, it seems
        # particularly important that we lock it down to a specific audited
        # version, instead of a tag like the other steps.
        uses: "AButler/upload-release-assets@ec6d3263266dc57eb6645b5f75e827987f7c217d"
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: "sdist-test/bundle/*.{tar.gz,sha}"

  lint:
    runs-on: "ubuntu-latest"
    container: "haskell:8.10.7-stretch@sha256:100f8fb7d7d8d64adb5e106fe8136b8d4cbdc03aeb2cbd145a7597d74b69bafb"

    steps:
      - # We need a proper Git repository, but the checkout step will unpack a tarball instead of doing a clone
        # if the Git version is less than 2.18.
        name: "Install a newer version of Git"
        run: |
          . /etc/os-release
          echo deb http://deb.debian.org/debian "$VERSION_CODENAME"-backports main >> /etc/apt/sources.list
          apt-get update && apt-get install -y git/"$VERSION_CODENAME"-backports
      - uses: "actions/checkout@v2"

      - name: "Fix working directory ownership"
        run: |
          chown root:root .

      - uses: "actions/cache@v2"
        with:
          path: |
            /root/.stack
          key: "${{ runner.os }}-ubiqcous-lint-${{ hashFiles('stack.yaml') }}"

      - run: "ci/fix-home ci/run-hlint.sh --git"
        env:
          VERSION: "2.2.11"

  make-prerelease:
    runs-on: "ubuntu-latest"
    needs:
      - "build"
      - "lint"
    if: "${{ github.event_name == 'push' && needs.build.outputs.do-not-prerelease != 'true' }}"
    steps:
      - uses: "actions/download-artifact@v3"
      - uses: "ncipollo/release-action@v1.10.0"
        with:
          tag: "${{ needs.build.outputs.version }}"
          artifacts: "*-bundle/*"
          prerelease: true
          omitBody: true
      - uses: "actions/setup-node@v3"
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com" # TODO: remove this!
      - uses: "actions/checkout@v3"
      - name: "Publish npm package"
        working-directory: "npm-package"
        env:
          BUILD_VERSION: "${{ needs.build.outputs.version }}"
          NODE_AUTH_TOKEN: "${{ secrets.GITHUB_TOKEN }}" # TODO: change this!
        run: |
          src_version=$(node -pe 'require("./package.json").version')
          npm version --allow-same-version "$BUILD_VERSION"
          sed -i -e "s/--purs-ver=${src_version//./\\.}/--purs-ver=$BUILD_VERSION/" package.json

          npm publish --tag next
